### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by Spp595** [ga2mer/ha-zepp#7]
I compiled the application from the sources and installed the .zab file, but when the application starts, the inscription is loading ... and that's it. Installed via gadgetbridge

Собрал приложение из исходников и установил .zab файл, но при запуске приложения надпись loading...
Установил через gadgetbridge

**Comment by ga2mer** [comment]
Приложению необходим интернет и настройка, поэтому приложение работает только через Zepp (не Life и модифицированный для Mi Band 7)

Gadgetbridge пока что не имеет нужного функционала и просто устанавливает приложение
